/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as ClinicAppointmentsRouteImport } from './routes/clinic.appointments'
import { Route as ClinicAvailabilityRouteImport } from './routes/clinic.availability'
import { Route as ClinicPatientsRouteImport } from './routes/clinic.patients'
import { Route as ClinicProfileRouteImport } from './routes/clinic.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicAppointmentsRoute = ClinicAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicAvailabilityRoute = ClinicAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicPatientsRoute = ClinicPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicProfileRoute = ClinicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClinicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinic': typeof ClinicRouteWithChildren
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/availability': typeof ClinicAvailabilityRoute
  '/clinic/patients': typeof ClinicPatientsRoute
  '/clinic/profile': typeof ClinicProfileRoute
  '/clinic/': typeof ClinicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/availability': typeof ClinicAvailabilityRoute
  '/clinic/patients': typeof ClinicPatientsRoute
  '/clinic/profile': typeof ClinicProfileRoute
  '/clinic': typeof ClinicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinic': typeof ClinicRouteWithChildren
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/availability': typeof ClinicAvailabilityRoute
  '/clinic/patients': typeof ClinicPatientsRoute
  '/clinic/profile': typeof ClinicProfileRoute
  '/clinic/': typeof ClinicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clinic'
    | '/clinic/appointments'
    | '/clinic/availability'
    | '/clinic/patients'
    | '/clinic/profile'
    | '/clinic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clinic/appointments'
    | '/clinic/availability'
    | '/clinic/patients'
    | '/clinic/profile'
    | '/clinic'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clinic'
    | '/clinic/appointments'
    | '/clinic/availability'
    | '/clinic/patients'
    | '/clinic/profile'
    | '/clinic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClinicRoute: typeof ClinicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/': {
      id: '/clinic/'
      path: '/'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/appointments': {
      id: '/clinic/appointments'
      path: '/appointments'
      fullPath: '/clinic/appointments'
      preLoaderRoute: typeof ClinicAppointmentsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/availability': {
      id: '/clinic/availability'
      path: '/availability'
      fullPath: '/clinic/availability'
      preLoaderRoute: typeof ClinicAvailabilityRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/patients': {
      id: '/clinic/patients'
      path: '/patients'
      fullPath: '/clinic/patients'
      preLoaderRoute: typeof ClinicPatientsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/profile': {
      id: '/clinic/profile'
      path: '/profile'
      fullPath: '/clinic/profile'
      preLoaderRoute: typeof ClinicProfileRouteImport
      parentRoute: typeof ClinicRoute
    }
  }
}

interface ClinicRouteChildren {
  ClinicAppointmentsRoute: typeof ClinicAppointmentsRoute
  ClinicAvailabilityRoute: typeof ClinicAvailabilityRoute
  ClinicPatientsRoute: typeof ClinicPatientsRoute
  ClinicProfileRoute: typeof ClinicProfileRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
}

const ClinicRouteChildren: ClinicRouteChildren = {
  ClinicAppointmentsRoute: ClinicAppointmentsRoute,
  ClinicAvailabilityRoute: ClinicAvailabilityRoute,
  ClinicPatientsRoute: ClinicPatientsRoute,
  ClinicProfileRoute: ClinicProfileRoute,
  ClinicIndexRoute: ClinicIndexRoute,
}

const ClinicRouteWithChildren =
  ClinicRoute._addFileChildren(ClinicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClinicRoute: ClinicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
